# Generated by Django 6.0.2 on 2026-02-26 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=150)),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('bus_type', models.CharField(choices=[('AC_SEATER', 'AC Seater'), ('NONAC_SEATER', 'Non-AC Seater'), ('AC_SLEEPER', 'AC Sleeper'), ('NONAC_SLEEPER', 'Non-AC Sleeper')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('SEATER', 'Seater'), ('SLEEPER', 'Sleeper')], max_length=10)),
                ('deck', models.CharField(choices=[('LOWER', 'Lower'), ('UPPER', 'Upper')], default='LOWER', max_length=10)),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
            options={
                'unique_together': {('bus', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.route')),
            ],
            options={
                'unique_together': {('bus', 'journey_date', 'departure_time')},
            },
        ),
    ]
